services:
  auth-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: auth_user_dev
      POSTGRES_PASSWORD: auth_pass_dev
      POSTGRES_DB: auth_db_dev
    ports:
        - "5432:5432"
